version: 1.0.{build}

# Gunakan Windows dan macOS Catalina
matrix:
  fast_finish: true
  allow_failures:
    - image: macos-catalina

environment:
  nodejs_version: "18"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm install -g electron-builder

# Build untuk Windows dan macOS
build_script:
  - npm run build:win
  - npm run build:mac

artifacts:
  - path: dist/*
    name: BrowserUjian

cache:
  - node_modules
  - "%LOCALAPPDATA%\\electron\\Cache"
  - "~/Library/Caches/electron"
